import { Body, Controller, Get, HttpCode, Param, Post } from '@nestjs/common';
import { ApiBody, ApiOkResponse, ApiOperation, ApiParam, ApiTags } from '@nestjs/swagger';
import {
  createRoomSchema,
  roomIdSchema,
  type CreateRoomPayload,
  type RoomInfo,
  type RoomSummary,
} from '@pokerplan/shared';
import { Throttle } from '@nestjs/throttler';
import { z } from 'zod';
import { ZodValidationPipe } from '../common/zod-validation.pipe';
import { RoomsService } from './rooms.service';

const roomInfoExample: RoomInfo = {
  id: 'k7m2xq9fha',
  name: 'Sprint 42 refinement',
  deck: 'FIBONACCI',
  createdAt: '2026-01-01T09:00:00.000Z',
  participantCount: 5,
  storyCount: 8,
};

@ApiTags('rooms')
@Controller('rooms')
export class RoomsController {
  constructor(private readonly rooms: RoomsService) {}

  @Post()
  @HttpCode(201)
  @Throttle({ default: { limit: 10, ttl: 60_000 } })
  @ApiOperation({
    summary: 'Create a room',
    description:
      'The `guestToken` is a random secret generated by the browser. Whoever connects to the room with the same token becomes the facilitator.',
  })
  @ApiBody({ schema: z.toJSONSchema(createRoomSchema, { io: 'input' }) as object })
  @ApiOkResponse({ schema: { example: roomInfoExample } })
  create(
    @Body(new ZodValidationPipe(createRoomSchema)) body: CreateRoomPayload,
  ): Promise<RoomInfo> {
    return this.rooms.create(body);
  }

  @Get(':roomId')
  @ApiOperation({ summary: 'Public room info (used before joining)' })
  @ApiParam({ name: 'roomId', example: roomInfoExample.id })
  @ApiOkResponse({ schema: { example: roomInfoExample } })
  get(@Param('roomId', new ZodValidationPipe(roomIdSchema)) roomId: string): Promise<RoomInfo> {
    return this.rooms.getInfo(roomId);
  }

  @Get(':roomId/summary')
  @ApiOperation({ summary: 'Session history: stories, rounds, votes and final estimates' })
  @ApiParam({ name: 'roomId', example: roomInfoExample.id })
  summary(
    @Param('roomId', new ZodValidationPipe(roomIdSchema)) roomId: string,
  ): Promise<RoomSummary> {
    return this.rooms.getSummary(roomId);
  }
}
